name: Test API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test API endpoints
      run: |
        python -c "
        import subprocess
        import time
        import requests
        import sys
        
        # Start the app in background
        proc = subprocess.Popen([sys.executable, 'app.py'], 
                               stdout=subprocess.PIPE, 
                               stderr=subprocess.PIPE)
        
        # Wait for app to start
        time.sleep(5)
        
        try:
            # Test health endpoint
            response = requests.get('http://localhost:5000/health')
            assert response.status_code == 200
            print('✓ Health check passed')
            
            # Test wimbledon endpoint
            response = requests.get('http://localhost:5000/wimbledon?year=2021')
            assert response.status_code == 200
            print('✓ Wimbledon endpoint test passed')
            
        except Exception as e:
            print(f'✗ Test failed: {e}')
            sys.exit(1)
        finally:
            proc.terminate()
        "
